apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: stage-cd-pipeline
spec:
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: deploy-image-no-replace
      taskRef:
        name: deploy-using-kubectl-without-replacement
      resources:
        inputs:
          - name: source
            resource: source-repo
      params:
      - name: PATHTODEPLOYMENT
        value: deploy
      - name: NAMESPACE
        value: stage-environment
    